[package]
name = "graph-base"
version = "0.1.4"
edition = "2021"
license = "MIT"
description = "A Rust library for graph data structures and algorithms"

[workspace]
members = []

[features]
default = []

[dependencies]
rand = "0.9.1"
